name: PlatformIO CI

on: [push, pull_request]

jobs:
  build:
    strategy:
     matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project Environment ESP8266 - ESP01-1M
        run: pio run -e esp01_1m

      - name: Build PlatformIO Project Environment ESP8266 - ESP12E
        run: pio run -e esp12e
